### ISSUE TITLE
Bad data in a corrective action tag breaks scraper

### ISSUE THREAD

**Issue by bschoenfeld** [Code4HR/open-health-inspection-scraper#23]
[This report](http://www.healthspace.com/Clients/VDH/Norfolk/Norolk_Website.nsf/Food-InspectionDetails?OpenView&RestrictToCategory=241B4D1CD3603F1D85257C2B00767F91&Count=1000) has some bad data in the sixth item. There is a tag in the correction text that shouldn't be there.

get_violations() in scraper.py breaks on this line when trying to process this violation:
```
'correction': ' '.join([tag.string for tag in details[1].contents if tag.name == 'font']).strip(),
```

**Comment by ttavenner** [comment]
Marking this as won't fix and closing. Since the page design has completely changed and we are re-writing the scraper from the ground up this will either be worked out naturally or will pop up again in development.
