### ISSUE TITLE
Implement robust duplicate checking

### ISSUE THREAD

**Issue by wbprice** [Code4HR/open-health-inspection-scraper#29]
Sometimes different versions of a single restaurant appear in Healthspaces data and are filtered down into the app.  Ex:

![screen shot 2014-12-04 at 7 22 34 am](https://cloud.githubusercontent.com/assets/2590422/5298231/c3eed148-7b86-11e4-8902-38caed26b034.png)

In this case, the information for http://openhealthinspection.com/#/vendor/yummy-wok-811-brandon is a superset of what's contained in http://openhealthinspection.com/#/vendor/yummy-wok-811-brandon-ave.   The name is the same but the address is subtly different.

For this case, a solution might be to check if the addresses and names are similar, and then compare the inspections objects against each other to check for an overlap.

**Comment by stanzheng** [comment]
So I noticed the entry '811 Brandon' looks like it is the more most up to date entries and the other one is stale data.

http://www.healthspace.com/Clients/VDH/Norfolk/Norolk_Website.nsf/Food-FacilityHistory?OpenView&RestrictToCategory=278629BC4934F02D852578240071AC4F

**Comment by ttavenner** [comment]
Paulo discovered that each vendor has a unique ID which is embedded in the URL. We are now pulling this out into a separate field so duplicate vendors shouldn't be an issue.
