### ISSUE TITLE
Double Listing

### ISSUE THREAD

**Issue by jalbertbowden** [Code4HR/open-health-inspection-scraper#31]
ever notice that norfolk is listed twice under N, but the second link goes to ptown?
is that taken into consideration when scraping?
http://www.healthspace.com/Clients/VDH/VDH_Website.nsf

**Comment by ttavenner** [comment]
This shouldn't be an issue any more. We don't grab any actual data from that list, just the link. Besides the address we store two location fields: locality which currently default to the health district i.e. Norfolk Health District and Portsmouth Health district; and city which we get from the address fields on each vendor. We used to get information from this list but as you can see it has its issues. They also still misspell Norfolk in the URL.

**Comment by jalbertbowden** [comment]
lol....i saw that the url too. i'm going to contact them and let them know. not sure what that'll do to your scrape, but i'll keep you posted to anything i hear back.
