### ISSUE TITLE
Change in Healthspace URL format

### ISSUE THREAD

**Issue by ttavenner** [Code4HR/open-health-inspection-scraper#32]
They have implemented a new ASP-based site with splash pages. all the URLs have changed. The scraper will need some significant overhaul to get working again.

**Comment by kmcurry** [comment]
Major bummer. :frowning:

**Comment by ttavenner** [comment]
It looks like only some of the health districts have changed over to the new format. So a probable course of actions is to identify these and shunt them off to a separate process that correctly scrapes the new format. This would make the process more sustainable if/when more districts make the switch without throwing out the districts still on the old format.

**Comment by ttavenner** [comment]
I had a bit of time to look at this last night and it isn't just an issue with the URL formats changing. The lists of establishments now use Javascript to build the URL to the establishment detail page. I tested it to be sure and there is no fallback, if you turn off javascript the page no longer functions. This will make it difficult/impossible to identify a list of establishments on the page without identifying and replicating the function to build the URL. The difficulty level on this task just went up quite a bit.

**Comment by ttavenner** [comment]
Closing this. We have started work on a new code base to handle this issue and I will be creating new issues for specific tasks.
